# Development and Test environment configurations are listed here
# for convenience but generally shouldn't be used.
# 
# Replace YOUR_APP with the heroku app name and YOUR_TOKEN with the
# same token used in private_pub.yml of your rails project.

production:
  server: "http://omnistrimfaye.herokuapp.com/faye"
  secret_token: "omnistrim"
  signature_expiration: 7200 # one hour


